name: Deploy Frontend

on:
  push:
    branches: [ main ]
    paths: [ 'frontend/**' ]  # Only trigger when frontend directory changes
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Validate Frontend Files
        run: |
          cd frontend
          # Check if required files exist
          if [ ! -f "index.html" ]; then echo "Error: index.html not found"; exit 1; fi
          if [ ! -f "style.css" ]; then echo "Error: style.css not found"; exit 1; fi
          if [ ! -f "script.js" ]; then echo "Error: script.js not found"; exit 1; fi
          if [ ! -f "config.js" ]; then echo "Error: config.js not found"; exit 1; fi
          echo "All required files are present"
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend 